// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://thwstctgxtuednngrbop.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRod3N0Y3RneHR1ZWRubmdyYm9wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3NzYzMDAsImV4cCI6MjA2NzM1MjMwMH0.w2iD4WXgdXskg_op90vn_cMdRdM6w7AQljzh2ZRB0eM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});